// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'm_vattu.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

_$MVatTuImpl _$$MVatTuImplFromJson(Map<String, dynamic> json) => _$MVatTuImpl(
      maCty: json['ma_cty'] as String?,
      maVt: json['ma_vt'] as String?,
      tenVt: json['ten_vt'] as String?,
      tenVt1: json['ten_vt1'] as String?,
      dvt: json['dvt'] as String?,
      loai: json['loai'] as String?,
      isTonKho: json['iston_kho'] as bool?,
      isTonViTri: json['iston_vitri'] as bool?,
      isTonLo: json['iston_lo'] as bool?,
      giaTon: json['gia_ton'] as String?,
      tonMin: (json['ton_min'] as num?)?.toInt(),
      tonMax: (json['ton_max'] as num?)?.toInt(),
      maNhvt: json['ma_nhvt'] as String?,
      maPlvt1: json['ma_plvt1'] as String?,
      maPlvt2: json['ma_plvt2'] as String?,
      maPlvt3: json['ma_plvt3'] as String?,
      maKho: json['ma_kho'] as String?,
      maViTri: json['ma_vitri'] as String?,
      maTsgtgt: json['ma_tsgtgt'] as String?,
      maTsnk: json['ma_tsnk'] as String?,
      tsXk: (json['ts_xk'] as num?)?.toInt(),
      maTsttdb: json['ma_tsttdb'] as String?,
      tkVt: json['tk_vt'] as String?,
      tkDt: json['tk_dt'] as String?,
      tkDtnb: json['tk_dtnb'] as String?,
      tkGv: json['tk_gv'] as String?,
      tkTl: json['tk_tl'] as String?,
      tkCk: json['tk_ck'] as String?,
      tkDd: json['tk_dd'] as String?,
      giaMua: (json['gia_mua'] as num?)?.toInt(),
      giaBan: (json['gia_ban'] as num?)?.toInt(),
      hanDung: (json['han_dung'] as num?)?.toInt(),
      maNsx: json['ma_nsx'] as String?,
      nguonGoc: json['nguon_goc'] as String?,
      hinhAnh: json['hinh_anh'] as String?,
      moTa: json['mo_ta'] as String?,
      tgBh: json['tg_bh'] as String?,
      isKsd: json['isksd'] as bool?,
      cDate: json['cdate'] as String?,
      cUser: json['cuser'] as String?,
      lDate: json['ldate'] as String?,
      lUser: json['luser'] as String?,
      tenVt2: json['ten_vt2'] as String?,
      maPlvt4: json['ma_plvt4'] as String?,
      moTa1: json['mo_ta1'] as String?,
      moTa2: json['mo_ta2'] as String?,
      maTrangThai: json['ma_trangthai'] as String?,
      ngayHieuLuc: json['ngay_hieuluc'] as String?,
      ngayHetHan: json['ngay_hethan'] as String?,
      tkKm: json['tk_km'] as String?,
      isHoanThanh: json['ishoanthanh'] as bool?,
      nguoiHoanThanh: json['nguoi_hoanthanh'] as String?,
      ngayHoanThanh: json['ngay_hoanthanh'] as String?,
      barcode: json['barcode'] as String?,
    );

Map<String, dynamic> _$$MVatTuImplToJson(_$MVatTuImpl instance) =>
    <String, dynamic>{
      'ma_cty': instance.maCty,
      'ma_vt': instance.maVt,
      'ten_vt': instance.tenVt,
      'ten_vt1': instance.tenVt1,
      'dvt': instance.dvt,
      'loai': instance.loai,
      'iston_kho': instance.isTonKho,
      'iston_vitri': instance.isTonViTri,
      'iston_lo': instance.isTonLo,
      'gia_ton': instance.giaTon,
      'ton_min': instance.tonMin,
      'ton_max': instance.tonMax,
      'ma_nhvt': instance.maNhvt,
      'ma_plvt1': instance.maPlvt1,
      'ma_plvt2': instance.maPlvt2,
      'ma_plvt3': instance.maPlvt3,
      'ma_kho': instance.maKho,
      'ma_vitri': instance.maViTri,
      'ma_tsgtgt': instance.maTsgtgt,
      'ma_tsnk': instance.maTsnk,
      'ts_xk': instance.tsXk,
      'ma_tsttdb': instance.maTsttdb,
      'tk_vt': instance.tkVt,
      'tk_dt': instance.tkDt,
      'tk_dtnb': instance.tkDtnb,
      'tk_gv': instance.tkGv,
      'tk_tl': instance.tkTl,
      'tk_ck': instance.tkCk,
      'tk_dd': instance.tkDd,
      'gia_mua': instance.giaMua,
      'gia_ban': instance.giaBan,
      'han_dung': instance.hanDung,
      'ma_nsx': instance.maNsx,
      'nguon_goc': instance.nguonGoc,
      'hinh_anh': instance.hinhAnh,
      'mo_ta': instance.moTa,
      'tg_bh': instance.tgBh,
      'isksd': instance.isKsd,
      'cdate': instance.cDate,
      'cuser': instance.cUser,
      'ldate': instance.lDate,
      'luser': instance.lUser,
      'ten_vt2': instance.tenVt2,
      'ma_plvt4': instance.maPlvt4,
      'mo_ta1': instance.moTa1,
      'mo_ta2': instance.moTa2,
      'ma_trangthai': instance.maTrangThai,
      'ngay_hieuluc': instance.ngayHieuLuc,
      'ngay_hethan': instance.ngayHetHan,
      'tk_km': instance.tkKm,
      'ishoanthanh': instance.isHoanThanh,
      'nguoi_hoanthanh': instance.nguoiHoanThanh,
      'ngay_hoanthanh': instance.ngayHoanThanh,
      'barcode': instance.barcode,
    };
