// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'm_thau.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

_$MThauImpl _$$MThauImplFromJson(Map<String, dynamic> json) => _$MThauImpl(
      thang: json['Thang'] as String? ?? '',
      tenNv: json['ten_nv'] as String? ?? '',
      maNv: json['ma_nv'] as String? ?? '',
      tenKh: json['ten_kh'] as String? ?? '',
      maVt: json['ma_vt'] as String? ?? '',
      tenVt: json['ten_vt'] as String? ?? '',
      tenNhvt: json['ten_nhvt'] as String? ?? '',
      slThau: (json['SLThau'] as num?)?.toDouble() ?? 0.0,
      tienThau: (json['TienThau'] as num?)?.toDouble() ?? 0.0,
      slThau1: (json['SLThau1'] as num?)?.toDouble() ?? 0.0,
      tienThau1: (json['TienThau1'] as num?)?.toDouble() ?? 0.0,
      slThauCungKy: (json['SLThauCungKy'] as num?)?.toDouble() ?? 0.0,
      tienThauCungKy: (json['TienThauCungKy'] as num?)?.toDouble() ?? 0.0,
      slThucHien: (json['SLThucHien'] as num?)?.toDouble() ?? 0.0,
      tienThucHien: (json['TienThucHien'] as num?)?.toDouble() ?? 0.0,
      slThucHienCungKy: (json['SLThucHienCungKy'] as num?)?.toDouble() ?? 0.0,
      tienThucHienCungKy:
          (json['TienThucHienCungKy'] as num?)?.toDouble() ?? 0.0,
      slTonThau: (json['SLTonThau'] as num?)?.toDouble() ?? 0.0,
      tienTonThau: (json['TienTonThau'] as num?)?.toDouble() ?? 0.0,
      slTonThau1: (json['SLTonThau1'] as num?)?.toDouble() ?? 0.0,
      tienTonThau1: (json['TienTonThau1'] as num?)?.toDouble() ?? 0.0,
      slBoThau: (json['SLBoThau'] as num?)?.toDouble() ?? 0.0,
      tienBoThau: (json['TienBoThau'] as num?)?.toDouble() ?? 0.0,
      sumSlThucHien: (json['SumSLThucHien'] as num?)?.toDouble() ?? 0.0,
      sumTienThucHien: (json['SumTienThucHien'] as num?)?.toDouble() ?? 0.0,
      slThucHienTr: (json['SLThucHien_tr'] as num?)?.toDouble() ?? 0.0,
      tienThucHienTr: (json['TienThucHien_tr'] as num?)?.toDouble() ?? 0.0,
      slThauTr: (json['SLThau_tr'] as num?)?.toDouble() ?? 0.0,
      tienThauTr: (json['TienThau_tr'] as num?)?.toDouble() ?? 0.0,
      slTonThauTr: (json['SLTonThau_tr'] as num?)?.toDouble() ?? 0.0,
      tienTonThauTr: (json['TienTonThau_tr'] as num?)?.toDouble() ?? 0.0,
      slTrungThau: (json['sl_trungthau'] as num?)?.toDouble() ?? 0.0,
      tienTrungThau: (json['tien_trungthau'] as num?)?.toDouble() ?? 0.0,
      slCaiThau: (json['sl_caithau'] as num?)?.toDouble() ?? 0.0,
      tienCaiThau: (json['tien_caithau'] as num?)?.toDouble() ?? 0.0,
      tenNhkh: json['ten_nhkh'] as String? ?? '',
      tenChinhanh: json['ten_chinhanh'] as String? ?? '',
    );

Map<String, dynamic> _$$MThauImplToJson(_$MThauImpl instance) =>
    <String, dynamic>{
      'Thang': instance.thang,
      'ten_nv': instance.tenNv,
      'ma_nv': instance.maNv,
      'ten_kh': instance.tenKh,
      'ma_vt': instance.maVt,
      'ten_vt': instance.tenVt,
      'ten_nhvt': instance.tenNhvt,
      'SLThau': instance.slThau,
      'TienThau': instance.tienThau,
      'SLThau1': instance.slThau1,
      'TienThau1': instance.tienThau1,
      'SLThauCungKy': instance.slThauCungKy,
      'TienThauCungKy': instance.tienThauCungKy,
      'SLThucHien': instance.slThucHien,
      'TienThucHien': instance.tienThucHien,
      'SLThucHienCungKy': instance.slThucHienCungKy,
      'TienThucHienCungKy': instance.tienThucHienCungKy,
      'SLTonThau': instance.slTonThau,
      'TienTonThau': instance.tienTonThau,
      'SLTonThau1': instance.slTonThau1,
      'TienTonThau1': instance.tienTonThau1,
      'SLBoThau': instance.slBoThau,
      'TienBoThau': instance.tienBoThau,
      'SumSLThucHien': instance.sumSlThucHien,
      'SumTienThucHien': instance.sumTienThucHien,
      'SLThucHien_tr': instance.slThucHienTr,
      'TienThucHien_tr': instance.tienThucHienTr,
      'SLThau_tr': instance.slThauTr,
      'TienThau_tr': instance.tienThauTr,
      'SLTonThau_tr': instance.slTonThauTr,
      'TienTonThau_tr': instance.tienTonThauTr,
      'sl_trungthau': instance.slTrungThau,
      'tien_trungthau': instance.tienTrungThau,
      'sl_caithau': instance.slCaiThau,
      'tien_caithau': instance.tienCaiThau,
      'ten_nhkh': instance.tenNhkh,
      'ten_chinhanh': instance.tenChinhanh,
    };
