// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'model/dtos/common/local_message.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
      id: const obx_int.IdUid(1, 495564043465255214),
      name: 'LocalMessage',
      lastPropertyId: const obx_int.IdUid(9, 2500880559770335787),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 1659026219682293011),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 1897789813080134736),
            name: 'title',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 2843055240731026205),
            name: 'body',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 3150832099561941780),
            name: 'createDate',
            type: 10,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 2347947096711290723),
            name: 'refData',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 3057067304349375164),
            name: 'docType',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(7, 728946525121825439),
            name: 'cloudId',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(8, 8171803758164870313),
            name: 'imageUrl',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(9, 2500880559770335787),
            name: 'summaryText',
            type: 9,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[])
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore(
    {String? directory,
    int? maxDBSizeInKB,
    int? maxDataSizeInKB,
    int? fileMode,
    int? maxReaders,
    bool queriesCaseSensitiveDefault = true,
    String? macosApplicationGroup}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(getObjectBoxModel(),
      directory: directory ?? (await defaultStoreDirectory()).path,
      maxDBSizeInKB: maxDBSizeInKB,
      maxDataSizeInKB: maxDataSizeInKB,
      fileMode: fileMode,
      maxReaders: maxReaders,
      queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
      macosApplicationGroup: macosApplicationGroup);
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
      entities: _entities,
      lastEntityId: const obx_int.IdUid(1, 495564043465255214),
      lastIndexId: const obx_int.IdUid(0, 0),
      lastRelationId: const obx_int.IdUid(0, 0),
      lastSequenceId: const obx_int.IdUid(0, 0),
      retiredEntityUids: const [],
      retiredIndexUids: const [],
      retiredPropertyUids: const [],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, obx_int.EntityDefinition>{
    LocalMessage: obx_int.EntityDefinition<LocalMessage>(
        model: _entities[0],
        toOneRelations: (LocalMessage object) => [],
        toManyRelations: (LocalMessage object) => {},
        getId: (LocalMessage object) => object.id,
        setId: (LocalMessage object, int id) {
          object.id = id;
        },
        objectToFB: (LocalMessage object, fb.Builder fbb) {
          final titleOffset =
              object.title == null ? null : fbb.writeString(object.title!);
          final bodyOffset =
              object.body == null ? null : fbb.writeString(object.body!);
          final refDataOffset =
              object.refData == null ? null : fbb.writeString(object.refData!);
          final docTypeOffset = fbb.writeString(object.docType);
          final imageUrlOffset = object.imageUrl == null
              ? null
              : fbb.writeString(object.imageUrl!);
          final summaryTextOffset = object.summaryText == null
              ? null
              : fbb.writeString(object.summaryText!);
          fbb.startTable(10);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, titleOffset);
          fbb.addOffset(2, bodyOffset);
          fbb.addInt64(3, object.createDate?.millisecondsSinceEpoch);
          fbb.addOffset(4, refDataOffset);
          fbb.addOffset(5, docTypeOffset);
          fbb.addInt64(6, object.cloudId);
          fbb.addOffset(7, imageUrlOffset);
          fbb.addOffset(8, summaryTextOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final createDateValue =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 10);
          final idParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          final docTypeParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 14, '');
          final titleParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 6);
          final bodyParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 8);
          final cloudIdParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 16, 0);
          final createDateParam = createDateValue == null
              ? null
              : DateTime.fromMillisecondsSinceEpoch(createDateValue);
          final refDataParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 12);
          final imageUrlParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 18);
          final summaryTextParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 20);
          final object = LocalMessage(
              id: idParam,
              docType: docTypeParam,
              title: titleParam,
              body: bodyParam,
              cloudId: cloudIdParam,
              createDate: createDateParam,
              refData: refDataParam,
              imageUrl: imageUrlParam,
              summaryText: summaryTextParam);

          return object;
        })
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [LocalMessage] entity fields to define ObjectBox queries.
class LocalMessage_ {
  /// See [LocalMessage.id].
  static final id =
      obx.QueryIntegerProperty<LocalMessage>(_entities[0].properties[0]);

  /// See [LocalMessage.title].
  static final title =
      obx.QueryStringProperty<LocalMessage>(_entities[0].properties[1]);

  /// See [LocalMessage.body].
  static final body =
      obx.QueryStringProperty<LocalMessage>(_entities[0].properties[2]);

  /// See [LocalMessage.createDate].
  static final createDate =
      obx.QueryDateProperty<LocalMessage>(_entities[0].properties[3]);

  /// See [LocalMessage.refData].
  static final refData =
      obx.QueryStringProperty<LocalMessage>(_entities[0].properties[4]);

  /// See [LocalMessage.docType].
  static final docType =
      obx.QueryStringProperty<LocalMessage>(_entities[0].properties[5]);

  /// See [LocalMessage.cloudId].
  static final cloudId =
      obx.QueryIntegerProperty<LocalMessage>(_entities[0].properties[6]);

  /// See [LocalMessage.imageUrl].
  static final imageUrl =
      obx.QueryStringProperty<LocalMessage>(_entities[0].properties[7]);

  /// See [LocalMessage.summaryText].
  static final summaryText =
      obx.QueryStringProperty<LocalMessage>(_entities[0].properties[8]);
}
