// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'm_invoice.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

_$MInvoiceImpl _$$MInvoiceImplFromJson(Map<String, dynamic> json) =>
    _$MInvoiceImpl(
      ma_cty: json['ma_cty'] as String,
      stt_rec: json['stt_rec'] as String,
      ma_ct: json['ma_ct'] as String,
      ma_kh: json['ma_kh'] as String,
      ten_kh: json['ten_kh'] as String,
      dia_chi: json['dia_chi'] as String,
      ma_so_thue: json['ma_so_thue'] as String,
      tel: json['tel'] as String,
      fax: json['fax'] as String,
      nguoi_gd: json['nguoi_gd'] as String,
      dien_giai: json['dien_giai'] as String,
      ma_dktt: json['ma_dktt'] as String,
      han_ck_dktt: (json['han_ck_dktt'] as num).toInt(),
      tl_ck_dktt: (json['tl_ck_dktt'] as num).toInt(),
      han_tt_dktt: (json['han_tt_dktt'] as num).toInt(),
      ls_qh_dktt: (json['ls_qh_dktt'] as num).toInt(),
      ngay_tt_dktt: DateTime.parse(json['ngay_tt_dktt'] as String),
      ma_hd: json['ma_hd'] as String,
      ma_nv: json['ma_nv'] as String,
      ma_nv1: json['ma_nv1'] as String,
      ma_nv2: json['ma_nv2'] as String,
      ma_nv3: json['ma_nv3'] as String,
      ma_nv4: json['ma_nv4'] as String,
      ma_nv5: json['ma_nv5'] as String,
      ma_nv6: json['ma_nv6'] as String,
      so_ct: json['so_ct'] as String,
      ngay_ct: DateTime.parse(json['ngay_ct'] as String),
      ma_nt: json['ma_nt'] as String,
      ty_gia: (json['ty_gia'] as num).toInt(),
      han_giao: DateTime.parse(json['han_giao'] as String),
      ma_htvc: json['ma_htvc'] as String,
      ma_dckh: json['ma_dckh'] as String,
      ten_dckh: json['ten_dckh'] as String,
      nguoi_gd_dckh: json['nguoi_gd_dckh'] as String,
      tel_dckh: json['tel_dckh'] as String,
      t_so_luong: (json['t_so_luong'] as num).toInt(),
      t_tien_nt2: (json['t_tien_nt2'] as num).toInt(),
      t_tien2: (json['t_tien2'] as num).toInt(),
      t_tien_ck_nt: (json['t_tien_ck_nt'] as num).toInt(),
      t_tien_ck: (json['t_tien_ck'] as num).toInt(),
      tl_ck_ds: (json['tl_ck_ds'] as num).toInt(),
      t_tien_ck_ds_nt: (json['t_tien_ck_ds_nt'] as num).toInt(),
      t_tien_ck_ds: (json['t_tien_ck_ds'] as num).toInt(),
      t_tien_nt3: (json['t_tien_nt3'] as num).toInt(),
      t_tien3: (json['t_tien3'] as num).toInt(),
      t_tien_ntkh: (json['t_tien_ntkh'] as num).toInt(),
      t_tienkh: (json['t_tienkh'] as num).toInt(),
      ma_tsgtgt: json['ma_tsgtgt'] as String,
      ts_gtgt: (json['ts_gtgt'] as num).toInt(),
      t_tien_thue_nt: (json['t_tien_thue_nt'] as num).toInt(),
      t_tien_thue: (json['t_tien_thue'] as num).toInt(),
      t_tien_tt_nt: (json['t_tien_tt_nt'] as num).toInt(),
      t_tien_tt: (json['t_tien_tt'] as num).toInt(),
      ispost_soct: json['ispost_soct'] as bool,
      issua_tt: json['issua_tt'] as bool,
      trang_thai: json['trang_thai'] as String,
      nguoi_duyet: json['nguoi_duyet'] as String,
      ngay_duyet: DateTime.parse(json['ngay_duyet'] as String),
      loai_sskt: json['loai_sskt'] as String,
      opt1: DateTime.parse(json['opt1'] as String),
      opt2: DateTime.parse(json['opt2'] as String),
      opt3: (json['opt3'] as num).toInt(),
      opt4: (json['opt4'] as num).toInt(),
      opt5: json['opt5'] as String,
      opt6: json['opt6'] as String,
      opt7: json['opt7'] as String,
      opt8: json['opt8'] as String,
      opt9: json['opt9'] as String,
      opt10: json['opt10'] as String,
      cdate: DateTime.parse(json['cdate'] as String),
      cuser: json['cuser'] as String,
      ldate: DateTime.parse(json['ldate'] as String),
      luser: json['luser'] as String,
      t_tien_ck_tsau_nt1: (json['t_tien_ck_tsau_nt1'] as num).toInt(),
      t_tien_ck_tsau1: (json['t_tien_ck_tsau1'] as num).toInt(),
      t_tien_ck_tsau_nt2: (json['t_tien_ck_tsau_nt2'] as num).toInt(),
      t_tien_ck_tsau2: (json['t_tien_ck_tsau2'] as num).toInt(),
      t_tien_ck_tsau_nt: (json['t_tien_ck_tsau_nt'] as num).toInt(),
      t_tien_ck_tsau: (json['t_tien_ck_tsau'] as num).toInt(),
      t_tien_nt4: (json['t_tien_nt4'] as num).toInt(),
      t_tien4: (json['t_tien4'] as num).toInt(),
      t_tien_thue_nt4: (json['t_tien_thue_nt4'] as num).toInt(),
      t_tien_thue4: (json['t_tien_thue4'] as num).toInt(),
      t_tien_tt_nt4: (json['t_tien_tt_nt4'] as num).toInt(),
      t_tien_tt4: (json['t_tien_tt4'] as num).toInt(),
      trang_thai_po: json['trang_thai_po'] as String,
      ten_nv1: json['ten_nv1'] as String,
      ten_nv2: json['ten_nv2'] as String,
      ten_nv3: json['ten_nv3'] as String,
      ten_nv4: json['ten_nv4'] as String,
      ten_nv5: json['ten_nv5'] as String,
      ten_nv6: json['ten_nv6'] as String,
      ma_gd: json['ma_gd'] as String,
      ma_dkgh: json['ma_dkgh'] as String,
      ma_httt: json['ma_httt'] as String,
      ma_pttt: json['ma_pttt'] as String,
      ma_lichtt: json['ma_lichtt'] as String,
      ghi_chu_gh: json['ghi_chu_gh'] as String,
      so_tk: json['so_tk'] as String,
      ten_ngh: json['ten_ngh'] as String,
      tinhtp: json['tinhtp'] as String,
      nguoi_dd: json['nguoi_dd'] as String,
      chuc_vu: json['chuc_vu'] as String,
      so_tk_cty: json['so_tk_cty'] as String,
      ten_ngh_cty: json['ten_ngh_cty'] as String,
      tinhtp_cty: json['tinhtp_cty'] as String,
      nguoi_dd_cty: json['nguoi_dd_cty'] as String,
      chuc_vu_cty: json['chuc_vu_cty'] as String,
      ten_dkgh: json['ten_dkgh'] as String,
      ten_httt: json['ten_httt'] as String,
      ten_pttt: json['ten_pttt'] as String,
      ten_lichtt: json['ten_lichtt'] as String,
      ten_dktt: json['ten_dktt'] as String,
      t_tien_nt5: (json['t_tien_nt5'] as num).toInt(),
      t_tien5: (json['t_tien5'] as num).toInt(),
      t_tien_nt6: (json['t_tien_nt6'] as num).toInt(),
      t_tien6: (json['t_tien6'] as num).toInt(),
      ma_thuetndn: json['ma_thuetndn'] as String,
      ts_tndn: (json['ts_tndn'] as num).toInt(),
      t_tien_tndn_nt: (json['t_tien_tndn_nt'] as num).toInt(),
      t_tien_tndn: (json['t_tien_tndn'] as num).toInt(),
      barcode: json['barcode'] as String,
      so_ct_onl: json['so_ct_onl'] as String,
      trang_thai_hg: json['trang_thai_hg'] as String,
      ngay_mongmuon_gh: DateTime.parse(json['ngay_mongmuon_gh'] as String),
      ma_rsm: json['ma_rsm'] as String,
      ma_sd: json['ma_sd'] as String,
      ma_pg: json['ma_pg'] as String,
      ma_kenhbh: json['ma_kenhbh'] as String,
    );

Map<String, dynamic> _$$MInvoiceImplToJson(_$MInvoiceImpl instance) =>
    <String, dynamic>{
      'ma_cty': instance.ma_cty,
      'stt_rec': instance.stt_rec,
      'ma_ct': instance.ma_ct,
      'ma_kh': instance.ma_kh,
      'ten_kh': instance.ten_kh,
      'dia_chi': instance.dia_chi,
      'ma_so_thue': instance.ma_so_thue,
      'tel': instance.tel,
      'fax': instance.fax,
      'nguoi_gd': instance.nguoi_gd,
      'dien_giai': instance.dien_giai,
      'ma_dktt': instance.ma_dktt,
      'han_ck_dktt': instance.han_ck_dktt,
      'tl_ck_dktt': instance.tl_ck_dktt,
      'han_tt_dktt': instance.han_tt_dktt,
      'ls_qh_dktt': instance.ls_qh_dktt,
      'ngay_tt_dktt': instance.ngay_tt_dktt.toIso8601String(),
      'ma_hd': instance.ma_hd,
      'ma_nv': instance.ma_nv,
      'ma_nv1': instance.ma_nv1,
      'ma_nv2': instance.ma_nv2,
      'ma_nv3': instance.ma_nv3,
      'ma_nv4': instance.ma_nv4,
      'ma_nv5': instance.ma_nv5,
      'ma_nv6': instance.ma_nv6,
      'so_ct': instance.so_ct,
      'ngay_ct': instance.ngay_ct.toIso8601String(),
      'ma_nt': instance.ma_nt,
      'ty_gia': instance.ty_gia,
      'han_giao': instance.han_giao.toIso8601String(),
      'ma_htvc': instance.ma_htvc,
      'ma_dckh': instance.ma_dckh,
      'ten_dckh': instance.ten_dckh,
      'nguoi_gd_dckh': instance.nguoi_gd_dckh,
      'tel_dckh': instance.tel_dckh,
      't_so_luong': instance.t_so_luong,
      't_tien_nt2': instance.t_tien_nt2,
      't_tien2': instance.t_tien2,
      't_tien_ck_nt': instance.t_tien_ck_nt,
      't_tien_ck': instance.t_tien_ck,
      'tl_ck_ds': instance.tl_ck_ds,
      't_tien_ck_ds_nt': instance.t_tien_ck_ds_nt,
      't_tien_ck_ds': instance.t_tien_ck_ds,
      't_tien_nt3': instance.t_tien_nt3,
      't_tien3': instance.t_tien3,
      't_tien_ntkh': instance.t_tien_ntkh,
      't_tienkh': instance.t_tienkh,
      'ma_tsgtgt': instance.ma_tsgtgt,
      'ts_gtgt': instance.ts_gtgt,
      't_tien_thue_nt': instance.t_tien_thue_nt,
      't_tien_thue': instance.t_tien_thue,
      't_tien_tt_nt': instance.t_tien_tt_nt,
      't_tien_tt': instance.t_tien_tt,
      'ispost_soct': instance.ispost_soct,
      'issua_tt': instance.issua_tt,
      'trang_thai': instance.trang_thai,
      'nguoi_duyet': instance.nguoi_duyet,
      'ngay_duyet': instance.ngay_duyet.toIso8601String(),
      'loai_sskt': instance.loai_sskt,
      'opt1': instance.opt1.toIso8601String(),
      'opt2': instance.opt2.toIso8601String(),
      'opt3': instance.opt3,
      'opt4': instance.opt4,
      'opt5': instance.opt5,
      'opt6': instance.opt6,
      'opt7': instance.opt7,
      'opt8': instance.opt8,
      'opt9': instance.opt9,
      'opt10': instance.opt10,
      'cdate': instance.cdate.toIso8601String(),
      'cuser': instance.cuser,
      'ldate': instance.ldate.toIso8601String(),
      'luser': instance.luser,
      't_tien_ck_tsau_nt1': instance.t_tien_ck_tsau_nt1,
      't_tien_ck_tsau1': instance.t_tien_ck_tsau1,
      't_tien_ck_tsau_nt2': instance.t_tien_ck_tsau_nt2,
      't_tien_ck_tsau2': instance.t_tien_ck_tsau2,
      't_tien_ck_tsau_nt': instance.t_tien_ck_tsau_nt,
      't_tien_ck_tsau': instance.t_tien_ck_tsau,
      't_tien_nt4': instance.t_tien_nt4,
      't_tien4': instance.t_tien4,
      't_tien_thue_nt4': instance.t_tien_thue_nt4,
      't_tien_thue4': instance.t_tien_thue4,
      't_tien_tt_nt4': instance.t_tien_tt_nt4,
      't_tien_tt4': instance.t_tien_tt4,
      'trang_thai_po': instance.trang_thai_po,
      'ten_nv1': instance.ten_nv1,
      'ten_nv2': instance.ten_nv2,
      'ten_nv3': instance.ten_nv3,
      'ten_nv4': instance.ten_nv4,
      'ten_nv5': instance.ten_nv5,
      'ten_nv6': instance.ten_nv6,
      'ma_gd': instance.ma_gd,
      'ma_dkgh': instance.ma_dkgh,
      'ma_httt': instance.ma_httt,
      'ma_pttt': instance.ma_pttt,
      'ma_lichtt': instance.ma_lichtt,
      'ghi_chu_gh': instance.ghi_chu_gh,
      'so_tk': instance.so_tk,
      'ten_ngh': instance.ten_ngh,
      'tinhtp': instance.tinhtp,
      'nguoi_dd': instance.nguoi_dd,
      'chuc_vu': instance.chuc_vu,
      'so_tk_cty': instance.so_tk_cty,
      'ten_ngh_cty': instance.ten_ngh_cty,
      'tinhtp_cty': instance.tinhtp_cty,
      'nguoi_dd_cty': instance.nguoi_dd_cty,
      'chuc_vu_cty': instance.chuc_vu_cty,
      'ten_dkgh': instance.ten_dkgh,
      'ten_httt': instance.ten_httt,
      'ten_pttt': instance.ten_pttt,
      'ten_lichtt': instance.ten_lichtt,
      'ten_dktt': instance.ten_dktt,
      't_tien_nt5': instance.t_tien_nt5,
      't_tien5': instance.t_tien5,
      't_tien_nt6': instance.t_tien_nt6,
      't_tien6': instance.t_tien6,
      'ma_thuetndn': instance.ma_thuetndn,
      'ts_tndn': instance.ts_tndn,
      't_tien_tndn_nt': instance.t_tien_tndn_nt,
      't_tien_tndn': instance.t_tien_tndn,
      'barcode': instance.barcode,
      'so_ct_onl': instance.so_ct_onl,
      'trang_thai_hg': instance.trang_thai_hg,
      'ngay_mongmuon_gh': instance.ngay_mongmuon_gh.toIso8601String(),
      'ma_rsm': instance.ma_rsm,
      'ma_sd': instance.ma_sd,
      'ma_pg': instance.ma_pg,
      'ma_kenhbh': instance.ma_kenhbh,
    };
